### ISSUE TITLE
Customising Header Image in ds106bank

### ISSUE THREAD

**Issue by eduToolkit** [cogdog/ds106bank#11]
Hello,

I understand if support is not maintained, but I'm building a resourcebank (http://assignments.edcamp.se/). When I add the header image [domain]/wp-admin/customize.php?return=%2Fwp-admin%2F&autofocus%5Bcontrol%5D=header_image ... it doesn't appear on the webpage. I can add it manually, but it would be nice if you could look if the wordpress template is correct.

My next challenge is to translate the information to Swedish, but I assume this is also being done manually.

Thank you for the support!

**Comment by cogdog** [comment]
Thanks for using the theme, your site looks like it is off to a great start.

Sadly the theme does not make use of the header image at all. I've had some plans to make this a possibility but have not done it yet as a feature.  Others have done it manually:

https://clmoocmb.educatorinnovator.org/home/
http://openlearning.ubc.ca/

Consider your issue a nudge to me to make it happen soon ;-)

**Comment by cogdog** [comment]
I felt like fiddling; I did not realize there was a remnant in there that enabled the customizer. I added code so it will use a thin header uploaded via the customizer (970px x 60px) because its part of the fixed header, but it's enough to add a logo. 

![bank-header](https://cloud.githubusercontent.com/assets/463038/26608762/27e67ab0-4552-11e7-899d-fc3424583b92.jpg)


It would take more work to allow a larger header, or maybe someone can figure it out better!

**Comment by eduToolkit** [comment]
This is great! I'm in contact with Jim Groom and in atumn I will start a DS106 inspired course in swedish. Will now try the update!

I also once managed to get the posts to show geographical location (example http://www.allthetoys.org/toy-map/), but can't get it to work... back to the manual I guess...
