### ISSUE TITLE
difficulty formatting embedded URLs

### ISSUE THREAD

**Issue by ehelminen** [cogdog/ds106bank#15]
Hi, I don't know if you're able to help me with this or not, but I'm struggling with having text wrap around or go underneath an embedded URL when someone submits an "assignment." See this page: http://dlc.middcreate.net/tinygig/examples/gig2-portfolio-on-middcreate/. The paragraph of explanation is stuck under the embedded link. I've also attached a screenshot of what I'm looking at, with the Developer Tools open.

If only I could change element.style from position:absolute; But I can't figure out how or where to do that. I've tried changing the CSS for the class wp-embedded-content, but it doesn't make a difference. I've also looked at some of the .php files, but am not exactly sure what I'm looking for.

Any advice or suggestions for me? Thanks!

![tiny-gig-formatting](https://user-images.githubusercontent.com/20567062/30297414-8fa2310c-96fc-11e7-9823-f75bc6b18398.png)

**Comment by cogdog** [comment]
Wordpress adds absolute positioning for auto embeds, I've never tried nor seen anyone try with an embedded URL but can see the problem.

Try adding to your CSS:

`
iframe.wp-embedded-content {
    position: relative !important;
}
`

This will override the absolute positioning that Wordpress adds with the url embed. I'm not sure if this will adversely affect other embeds (e.g. tweets and videos), it's only a guess right now. Please let me know. 

I like the Gigs, that's a lot of nice customizing of the interface.

**Comment by ehelminen** [comment]
Thanks for giving me the syntax. I had actually tried that, even with the "!important" marker, and it didn't do anything. But now that I see yours, I realize I had the semi-colon in the wrong place. 

Appreciate your feedback! And thanks for the kind words. I was going to send you a message when the site was complete so you could take a look... Spilled the beans by needing help before it was done. ;)

**Comment by cogdog** [comment]
An unrelated question, but wanted to ask seeing all the design customizations you have done... The bootstrap parent theme this is based on won't be updated. I did a short test, but it is possible that to roll all the customizations of the DS106 Bank into a single theme. That way you could do your mods as a child theme, making updates easier to manage.

Just checking your thoughts on this.

**Comment by ehelminen** [comment]
Seems like it would make sense. I haven't thought too much about how updates will work yet, although it did cross my mind that they might be a pain. (think I'm still in denial about that). I've made edits to CSS and a lot of the PHP files as well, so I shudder to think of what might be lost in updates, especially as I don't even fully understand the current structure or the way that Bootstrap is used here. I'm more of a novice with this stuff than it may look like on the surface. I don't think I've ever even used a Child Theme, although I understand why they're important and started to implement one once. 

So yes, I like your idea to roll all the customizations into a single theme and I'm wondering if there's anything I need to/can do to help you with that process, and what I might have to do once that's done. Open to talking more! Thanks.

**Comment by cogdog** [comment]
Once you start down making modifications to a theme, you have closed the door on being able to update w/o manual picking and editing. The way a child theme works is anything in it, like styles, or a different` single.php` supersedes the parent theme. And so if the parent theme is updated, you can do that and not lose your changes.

With qwhat I have done, the Assignment Bank theme is a Child of WP Bootstrap. In theory you might be able to do children of child themes (grandchildren) but it sounds fraught with peril.

Since WP Bootstrap will never be updated, if I combine them into one, you could then make your own child theme, with copies of the files you have modified. It might be a tad messy to get converted, but going forward it would mean your custom work can benefit from any featured I change (or more likely fix).

Might be a while before I get around to this, though.
