### ISSUE TITLE
Checkbox to eliminate/hide Examples & Tutorials aspects

### ISSUE THREAD

**Issue by econproph** [cogdog/ds106bank#6]
I'm using the DS106Bank to in a couple of slightly different use cases from the original Assignment Bank concept.  
In one of our use cases, we're using the DS106Bank theme to create college-wide, department- and program-level shared OER repositories and collections.   So instead of "assignment", I'm calling them "resources".  The create-assignment and browse-assignment functionality works great for this purpose. BUt in this case  "examples" and "tutorials" stuff isn't needed at all.   I've figured out thru the settings page and menu how to keep folks from accessing or creating the examples or tutorials.  

The issue is how to prevent display of the box and verbiage about "Do This Assignment" and "Tutorials for This Assignment".   In other words,  I need to: 
 1. Eliminate the box & verbiage about  "Do This Assignment"          "Tutorials for This Assignment"  etc.  

After checking with @cogdog , I think the best approach would be to add a simple check-off capability in settings to turn off this whole examples & tutorials functionality and also not display those boxes.  

Attached screenshot for what I'm talking about.  
![screenshot 2016-07-26 10 24 28](https://cloud.githubusercontent.com/assets/18156259/17188284/62965926-540a-11e6-989c-ed8b013c2cae.png)

**Comment by cogdog** [comment]
Thanks for the idea, Jim. I rolled in a new Bank Assignment option to give you this feature. Rather than a single checkbox, you can choose now to show:

- Examples and Tutorials (2 columns as is now)
- Just Examples (1 column)
- Just Tutorials (1 column)
- none (as you are asking)

Here is the new option

![display-single-options](https://cloud.githubusercontent.com/assets/463038/17188773/70bd7e56-53f3-11e6-8632-6fa189bb8d67.jpg)

A few examples:

**Both** (default now)
![vis-metaphor-bottom](https://cloud.githubusercontent.com/assets/463038/17188842/ba39c792-53f3-11e6-87ef-b70f292f6009.jpg)


**Examples Only**

![examples only](https://cloud.githubusercontent.com/assets/463038/17188809/971c9122-53f3-11e6-9ccc-5a633977a16a.jpg)

**Tutorials Only**
![resourcs-only](https://cloud.githubusercontent.com/assets/463038/17188818/a1d4a87a-53f3-11e6-87a3-56551fc4117b.jpg)

**Neither**
![neither](https://cloud.githubusercontent.com/assets/463038/17188828/ad935224-53f3-11e6-9bcd-27fe1e6d375d.jpg)
